FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# 97buy user api

97buy user API規格文件

# Group User

## Users Collection [/users]

### List All Users [GET]

取得所有會員
+ Response 200 (application/json)

    + Headers

        Request-Id: 01234567-89ab-cdef-0123-456789abcdef

    + Body

            [
                {
                    "email": "ryan20151016@gmail.com",
                    "nickname": "賴大帥",
                    "cellphone": "0952123456"
                },
                {
                    "email": "ken@gmail.com",
                    "nickname": "許心臟",
                    "cellphone": "0952654321"
                },
                {
                    "email": "jeff@gmail.com",
                    "nickname": "小廢物",
                    "cellphone": "0952999999"
                }
            ]

### Create a New User [POST]

新增會員
+ Request

        {
            "email": "ryan20151016@gmail.com",
            "nickname": "賴大帥",
            "cellphone": "0952123456",
        }

+ Response 200 (application/json)

    + Headers

            Location: /user/1

    + Body

            {
                "email": "ryan20151016@gmail.com",
                "nickname": "賴大帥",
                "cellphone": "0952123456",
            }

## User Collections [/users/{user_id}]

+ Parameters
    + user_id (required, number, `2`) ... ID of the user in form of an integer

### Get Single user [GET]

取得單一會員
+ Response 200 (application/json)
    + Headers

            Request-Id: 01234567-89ab-cdef-0123-456789abcdef

    + Body

            {
                "email": "ryan20151016@gmail.com",
                "nickname": "賴大帥",
                "cellphone": "0952123456",
            }

### Update Single User [PUT]

更新會員
+ Request

        {
            "email": "ryan20151016@gmail.com",
            "nickname": "賴大帥",
            "cellphone": "0952123456",
        }

+ Response 200 (application/json)
    + Headers

            Request-Id: 01234567-89ab-cdef-0123-456789abcdef

    + Body

            {
                "email": "ryan20151016@gmail.com",
                "nickname": "賴大帥",
                "cellphone": "0952123456",
            }



### Delete User [DELETE]

刪除會員
+ Request

        {
            "email": "ryan20151016@gmail.com",
            "nickname": "賴大帥",
            "cellphone": "0952123456",
        }

+ Response 200 (application/json)

    + Headers

            Location: /member/1

    + Body

            {
                "email": "ryan20151016@gmail.com",
                "nickname": "賴大帥",
                "cellphone": "0952123456",
            }
