FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# 97buy user api 規格文件

欄位說明
* id:             會員編號(ex:1)  
* fullname:       真實姓名(ex:賴璽丞)  
* nickname:       綽號(ex:賴大帥)  
* email:          電子郵件(ex:ryan20151016@gmail.com)  
* pwd:            密碼(ex:123456)  
* cellphone       手機(ex:0952123456)  
* birhtday        生日(ex:1988-08-26)  
* gender          性別(1:男, 2:女)  
* level           會員等級(0:管理者, 1:一般會員)

## 路由/users [/users]

### List All Users [GET]

取得所有會員
+ Request

    + Headers
    
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAxMC9zaWduaW4iLCJpYXQiOjE0ODEyOTAxNTIsImV4cCI6MTQ4MTI5Mzc1MiwibmJmIjoxNDgxMjkwMTUyLCJqdGkiOiIzNDVhNjNiNmQ2NWU1YWRkN2ViODJhNGM4YTAzNzJhZiJ9.bpuYr680kk6BWcDHk8c2Hw8uzNrDpOpnTg67JqC4pok


+ Response 200 (application/json)

    + Headers

            Request-Id: 01234567-89ab-cdef-0123-456789abcdef

    + Body

            [
                {
                    "id": "1",
                    "fullname":"賴璽丞",
                    "nickname": "賴大帥",
                    "email": "ryan20151016@gmail.com",
                    "pwd": "123455678",
                    "cellphone": "0952123456",
                    "birthday": "1988-08-26",
                    "gender": "男",
                    "level": "0"
                },
                {
                    "id": "2",
                    "fullname":"許東篁",
                    "nickname": "許心臟",
                    "email": "ken@gmail.com",
                    "pwd": "9999999",
                    "cellphone": "0952654321",
                    "birthday": "1983-05-23",
                    "gender": "男",
                    "level": "1"
                },
                {
                    "id": "3",
                    "fullname":"吳廣誠",
                    "nickname": "小廢物",
                    "email": "jeff@gmail.com",
                    "pwd": "88888",
                    "cellphone": "0952999999",
                    "birthday": "1989-01-06",
                    "gender": "女",
                    "level": "1"
                }
            ]

### Create a New User [POST]

新增會員
+ Request

        {
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAxMC9zaWduaW4iLCJpYXQiOjE0ODEyOTAxNTIsImV4cCI6MTQ4MTI5Mzc1MiwibmJmIjoxNDgxMjkwMTUyLCJqdGkiOiIzNDVhNjNiNmQ2NWU1YWRkN2ViODJhNGM4YTAzNzJhZiJ9.bpuYr680kk6BWcDHk8c2Hw8uzNrDpOpnTg67JqC4pok",
            "fullname":"賴璽丞",
            "nickname": "賴大帥",
            "email": "ryan20151016@gmail.com",
            "pwd": "123455678",
            "cellphone": "0952123456",
            "birthday": "1988-08-26",
            "gender": "男",
            "level": "1",
        }

+ Response 200 (application/json)

    + Headers

            Location: /user/1

    + Body

            {
                "fullname":"賴璽丞",
                "nickname": "賴大帥",
                "email": "ryan20151016@gmail.com",
                "pwd": "123455678",
                "cellphone": "0952123456",
                "birthday": "1988-08-26",
                "gender": "男",
                "level": "1",
            }

## User Collections [/users/{user_id}]

+ Parameters
    + user_id (required, number, `2`) ... ID of the user in form of an integer

### Get Single user [GET]

取得單一會員
+ Response 200 (application/json)
    + Headers

            Request-Id: 01234567-89ab-cdef-0123-456789abcdef

    + Body

            {
                "fullname":"賴璽丞",
                "nickname": "賴大帥",
                "email": "ryan20151016@gmail.com",
                "pwd": "123455678",
                "cellphone": "0952123456",
                "birthday": "1988-08-26",
                "gender": "男",
                "level": "1",
            }

### Update Single User [PUT]

更新會員
+ Request

        {
            "id": "2",
            "fullname":"許東篁",
            "nickname": "許心臟",
            "email": "ken@gmail.com",
            "pwd": "9999999",
            "cellphone": "0952654321",
            "birthday": "1983-05-23",
            "gender": "男",
            "level": "1",
        }

+ Response 200 (application/json)
    + Headers

            Request-Id: 01234567-89ab-cdef-0123-456789abcdef

    + Body

            {
                "id": "2",
                "fullname":"許東篁",
                "nickname": "許心臟",
                "email": "ken@gmail.com",
                "pwd": "9999999",
                "cellphone": "0952654321",
                "birthday": "1983-05-23",
                "gender": "男",
                "level": "1",
            }



### Delete User [DELETE]

刪除會員
+ Request

        {
            "id": "2",
            "fullname":"許東篁",
            "nickname": "許心臟",
            "email": "ken@gmail.com",
            "pwd": "9999999",
            "cellphone": "0952654321",
            "birthday": "1983-05-23",
            "gender": "男",
            "level": "1",
        }

+ Response 200 (application/json)

    + Headers

            Location: /member/1

    + Body

            {
                "id": "2",
                "fullname":"許東篁",
                "nickname": "許心臟",
                "email": "ken@gmail.com",
                "pwd": "9999999",
                "cellphone": "0952654321",
                "birthday": "1983-05-23",
                "gender": "男",
                "level": "1",
            }
